spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://trainingdb.ck1ayq0lncmp.ap-south-1.rds.amazonaws.com:3306/watercanapp_user_db
        username: anitha
        password: anitha 
    flyway: 
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://trainingdb.ck1ayq0lncmp.ap-south-1.rds.amazonaws.com:3306/watercanapp_user_db
        username: anitha
        password: anitha